### ISSUE TITLE
Is this really Kotlin?

### ISSUE THREAD

**Issue by TheJavaGuy** [jhipster/jhipster-sample-app-kotlin#2]
If this was really generated with the Kotlin blueprint, how come there is not a single `.kt` file in a project?

**Comment by deepu105** [comment]
Probably something went wrong during generation time. Ping @sendilkumarn

**Comment by sendilkumarn** [comment]
Nope it is not. I have no clue how it is getting created. Ping @jdubois

**Comment by sendilkumarn** [comment]
Updated this. :)
